version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    ignore:
      # Update only patch version of GE Maven extension
      - dependency-name: "com.gradle:gradle-enterprise-maven-extension"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
  # github-actions with directory: "/" only monitors .github/workflows
  # https://github.com/dependabot/dependabot-core/issues/6345
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gradle/download"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gradle/experiment-1"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gradle/experiment-2"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gradle/experiment-3"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gradle/experiment-config-cache"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/maven/download"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/maven/experiment-1"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/maven/experiment-2"
    schedule:
      interval: "daily"
      time: "02:00"
