name: Create Development Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  development_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: ./gradlew build githubRelease -i
        env:
          GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
